# .github/actions/setup-node-pnpm/action.yml

name: Setup Node.js and PNPM
description: Sets up Node.js and PNPM based on project configuration

runs:
  using: composite
  steps:
    - name: Setup PNPM
      uses: pnpm/action-setup@v4

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version-file: .nvmrc
        cache: pnpm